sudo: required
langauge: generic

services:
  - docker

before_install:
  - docker build -t sulinys/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test -- --coverage